### ISSUE TITLE
SimpleTrieFilter 中有bug

### ISSUE THREAD

**Issue by qiujiayu** [KimShen/double-array-trie#1]
SimpleTrieFilter 中的 filter 方法：

for(int index=0; index < buffer.length(); index+=1) {
            this.step(buffer, judgment, index);
        }

可以用这个字符串进行测试：
this.content="你把把邓小平怎么样了？辦證上哪儿去办？卖枪网站的地址是什么？枪决女犯枪决现场足球世界杯！";

**Comment by KimShen** [comment]
Fixed
